/*
 * This file is generated by jOOQ.
 */
package br.com.ibasi.jooq;


import br.com.ibasi.jooq.tables.FlywaySchemaHistory;
import br.com.ibasi.jooq.tables.Invoice;
import br.com.ibasi.jooq.tables.InvoiceItem;
import br.com.ibasi.jooq.tables.Product;
import br.com.ibasi.jooq.tables.records.FlywaySchemaHistoryRecord;
import br.com.ibasi.jooq.tables.records.InvoiceItemRecord;
import br.com.ibasi.jooq.tables.records.InvoiceRecord;
import br.com.ibasi.jooq.tables.records.ProductRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<InvoiceRecord> KEY_INVOICE_PRIMARY = Internal.createUniqueKey(Invoice.INVOICE, DSL.name("KEY_invoice_PRIMARY"), new TableField[] { Invoice.INVOICE.ID }, true);
    public static final UniqueKey<InvoiceItemRecord> KEY_INVOICE_ITEM_PRIMARY = Internal.createUniqueKey(InvoiceItem.INVOICE_ITEM, DSL.name("KEY_invoice_item_PRIMARY"), new TableField[] { InvoiceItem.INVOICE_ITEM.ID }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_PRIMARY"), new TableField[] { Product.PRODUCT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<InvoiceItemRecord, InvoiceRecord> FK_INVOICE_ITEM__INVOICE = Internal.createForeignKey(InvoiceItem.INVOICE_ITEM, DSL.name("fk_invoice_item__invoice"), new TableField[] { InvoiceItem.INVOICE_ITEM.INVOICE_ID }, Keys.KEY_INVOICE_PRIMARY, new TableField[] { Invoice.INVOICE.ID }, true);
    public static final ForeignKey<InvoiceItemRecord, ProductRecord> FK_INVOICE_ITEM__PRODUCT = Internal.createForeignKey(InvoiceItem.INVOICE_ITEM, DSL.name("fk_invoice_item__product"), new TableField[] { InvoiceItem.INVOICE_ITEM.PRODUCT_ID }, Keys.KEY_PRODUCT_PRIMARY, new TableField[] { Product.PRODUCT.ID }, true);
}
