/*
 * This file is generated by jOOQ.
 */
package br.com.ibasi.jooq;


import br.com.ibasi.jooq.tables.FlywaySchemaHistory;
import br.com.ibasi.jooq.tables.Invoice;
import br.com.ibasi.jooq.tables.InvoiceItem;
import br.com.ibasi.jooq.tables.Product;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>invoice</code>.
     */
    public static final Invoice INVOICE = Invoice.INVOICE;

    /**
     * The table <code>invoice_item</code>.
     */
    public static final InvoiceItem INVOICE_ITEM = InvoiceItem.INVOICE_ITEM;

    /**
     * The table <code>product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
