services:
  db:
    image: mysql:8.4.0
    command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --lc-time-names=pt_BR --mysql-native-password=ON
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    init: true
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql

  server:
    build: .
    environment:
      - TZ=America/Sao_Paulo
      - MAVEN_CONFIG=/home/.m2
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    ports:
      - "${SERVER_EXTERNAL_PORT}:3000"
      - "${SERVER_DEBUG_PORT}:5005"
    restart: always
    volumes:
      - ./:/home/app
      - maven-repo:/home/.m2

volumes:
  db:
  maven-repo:
