/*
 * This file is generated by jOOQ.
 */
package br.com.ibasi.jooq.tables;


import br.com.ibasi.jooq.DefaultSchema;
import br.com.ibasi.jooq.Keys;
import br.com.ibasi.jooq.tables.InvoiceItem.InvoiceItemPath;
import br.com.ibasi.jooq.tables.records.InvoiceRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Invoice extends TableImpl<InvoiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>invoice</code>
     */
    public static final Invoice INVOICE = new Invoice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoiceRecord> getRecordType() {
        return InvoiceRecord.class;
    }

    /**
     * The column <code>invoice.id</code>.
     */
    public final TableField<InvoiceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>invoice.datetime</code>.
     */
    public final TableField<InvoiceRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private Invoice(Name alias, Table<InvoiceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Invoice(Name alias, Table<InvoiceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>invoice</code> table reference
     */
    public Invoice(String alias) {
        this(DSL.name(alias), INVOICE);
    }

    /**
     * Create an aliased <code>invoice</code> table reference
     */
    public Invoice(Name alias) {
        this(alias, INVOICE);
    }

    /**
     * Create a <code>invoice</code> table reference
     */
    public Invoice() {
        this(DSL.name("invoice"), null);
    }

    public <O extends Record> Invoice(Table<O> path, ForeignKey<O, InvoiceRecord> childPath, InverseForeignKey<O, InvoiceRecord> parentPath) {
        super(path, childPath, parentPath, INVOICE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InvoicePath extends Invoice implements Path<InvoiceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InvoicePath(Table<O> path, ForeignKey<O, InvoiceRecord> childPath, InverseForeignKey<O, InvoiceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InvoicePath(Name alias, Table<InvoiceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InvoicePath as(String alias) {
            return new InvoicePath(DSL.name(alias), this);
        }

        @Override
        public InvoicePath as(Name alias) {
            return new InvoicePath(alias, this);
        }

        @Override
        public InvoicePath as(Table<?> alias) {
            return new InvoicePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<InvoiceRecord, Integer> getIdentity() {
        return (Identity<InvoiceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InvoiceRecord> getPrimaryKey() {
        return Keys.KEY_INVOICE_PRIMARY;
    }

    private transient InvoiceItemPath _invoiceItem;

    /**
     * Get the implicit to-many join path to the
     * <code>quarkus-graphql.invoice_item</code> table
     */
    public InvoiceItemPath invoiceItem() {
        if (_invoiceItem == null)
            _invoiceItem = new InvoiceItemPath(this, null, Keys.FK_INVOICE_ITEM__INVOICE.getInverseKey());

        return _invoiceItem;
    }

    @Override
    public Invoice as(String alias) {
        return new Invoice(DSL.name(alias), this);
    }

    @Override
    public Invoice as(Name alias) {
        return new Invoice(alias, this);
    }

    @Override
    public Invoice as(Table<?> alias) {
        return new Invoice(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoice rename(String name) {
        return new Invoice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoice rename(Name name) {
        return new Invoice(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoice rename(Table<?> name) {
        return new Invoice(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice where(Condition condition) {
        return new Invoice(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Invoice where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Invoice where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Invoice where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Invoice where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Invoice whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
