/*
 * This file is generated by jOOQ.
 */
package br.com.ibasi.jooq.tables.records;


import br.com.ibasi.jooq.tables.InvoiceItem;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvoiceItemRecord extends UpdatableRecordImpl<InvoiceItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>invoice_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>invoice_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>invoice_item.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>invoice_item.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>invoice_item.unit_value</code>.
     */
    public void setUnitValue(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>invoice_item.unit_value</code>.
     */
    public BigDecimal getUnitValue() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>invoice_item.invoice_id</code>.
     */
    public void setInvoiceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>invoice_item.invoice_id</code>.
     */
    public Integer getInvoiceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>invoice_item.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>invoice_item.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceItemRecord
     */
    public InvoiceItemRecord() {
        super(InvoiceItem.INVOICE_ITEM);
    }

    /**
     * Create a detached, initialised InvoiceItemRecord
     */
    public InvoiceItemRecord(Integer id, BigDecimal quantity, BigDecimal unitValue, Integer invoiceId, Integer productId) {
        super(InvoiceItem.INVOICE_ITEM);

        setId(id);
        setQuantity(quantity);
        setUnitValue(unitValue);
        setInvoiceId(invoiceId);
        setProductId(productId);
        resetChangedOnNotNull();
    }
}
