/*
 * This file is generated by jOOQ.
 */
package br.com.ibasi.jooq.tables.records;


import br.com.ibasi.jooq.tables.Invoice;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvoiceRecord extends UpdatableRecordImpl<InvoiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>invoice.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>invoice.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>invoice.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>invoice.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceRecord
     */
    public InvoiceRecord() {
        super(Invoice.INVOICE);
    }

    /**
     * Create a detached, initialised InvoiceRecord
     */
    public InvoiceRecord(Integer id, LocalDateTime datetime) {
        super(Invoice.INVOICE);

        setId(id);
        setDatetime(datetime);
        resetChangedOnNotNull();
    }
}
